
server:
  port: 5050

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: vendedor
      bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: true
    producer:
      bootstrap-servers: localhost:9092

kafka:
  schema-registry-server: http://localhost:8081